# -*- coding: utf-8 -*-
"""Exp1_RL Tools

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCLMJFbarTIXdbfaCDt3f9lJ7JoSMkNy

OPENAI's GYM
"""

pip install gym

"""keras-rl

"""

pip install keras-rl

"""Open-Spiel

"""

pip install open_spiel

"""TF Agents"""

!pip install --user tf-agents[reverb]

!export TF_USE_LEGACY_KERAS=1

!git clone https://github.com/tensorflow/agents.git

!cd agents

!git checkout v0.18.0

pip install tox

