from tkinter import *
master = Tk()
master.title("Doctor Appointment App")
l1=Label(master,text='Signup',font=("Arial Bold",30))
l1.grid(row=0,column=0)
Label1=Label(master, text='First Name:').grid(row=1)
Label2=Label(master, text='Last Name:').grid(row=2)
Label3=Label(master, text='Age:').grid(row=3)
Label4=Label(master, text='Gender:').grid(row=4)
var1 = IntVar()
Checkbutton(master, text='Male', variable=var1).grid(row=4, column=1)
var2 = IntVar()
Checkbutton(master, text='Female', variable=var2).grid(row=5, column=1)
Label5=Label(master, text='City:').grid(row=6)
Label6=Label(master, text='Address:').grid(row=7)
Label7=Label(master, text='User name:').grid(row=8)
Label8=Label(master, text='Password:').grid(row=9)
Label9=Label(master, text='Verify password:').grid(row=10)
e1 = Entry(master)
e2 = Entry(master)
e3=Entry(master)
e4=Entry(master)
e5=Entry(master)
e6=Entry(master)
e7=Entry(master)
e8=Entry(master)
e1.grid(row=1, column=1)
e2.grid(row=2, column=1)
e3.grid(row=3,column=1)
e4.grid(row=6,column=1)
e5.grid(row=7,column=1)
e6.grid(row=8,column=1)
e7.grid(row=9,column=1)
e8.grid(row=10,column=1)
b1=Button(master, text = 'Signup', bd = '5',command = master.destroy)
b2=Button(master, text = 'Clear', bd = '5',command = master.destroy)
b3=Button(master, text = 'Switch to login', bd = '5',command = master.destroy)
b1.grid(row=11,column=0)
b2.grid(row=11,column=1)
b3.grid(row=0,column=3)
print('First Name:', Label1)
print('Last Name:', Label1)
print('Age:', Label1)
print('Gender:', Label1)
print('City:', Label1)
print('Address:', Label1)
print('User name:', Label1)
print('Password:', Label1)
print('Verify password:', Label1)
mainloop()
